### ISSUE TITLE
Organização - Sprint 2

### ISSUE THREAD

**Issue by luanasoares0901** [Mylena-angelica/Debian-GCES-24.1#3]
Esta issue se destinará à organização do repositório, registrar combinados entre os membros.
## TO-DO 
- [x] Cria template issues
- [x] Criar Pages (design e home)
- [x] Divisão das tarefas
- [ ] Decisões sobre as reuniões de alinhamento
- [x] Divisão em subgrupos, pareamento

**Comment by luanasoares0901** [comment]
# Divisão de tarefas

- @luanasoares0901 e @Mylena-angelica Pages
- @Jvsoutomaior Reuniões de alinhamento
- @HenriPucci Template issues
- @leonardogonmac Template de Entregável

**Comment by luanasoares0901** [comment]
## Pareamento Sprint 2
Pareamento feito de acordo com estágios de contribuição
- @Mylena-angelica e @leonardogonmac e @analuizargds 
- @igorpenhaa e @BrunoRiibeiro 
- @luanasoares0901 e Marcelo
- @Hellen159 e @ingridSCarvalho 
- Guilherme e @HenriPucci e @Jvsoutomaior

**Comment by Mylena-angelica** [comment]
Aguardando a decisão do dia da reunião.

**Comment by Mylena-angelica** [comment]
Issue fechada.
